org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false

minecraft_version = 1.21.1
minecraft_version_range = [1.21.1,1.21.2)
neo_version = 21.1.251
neo_version_range = [21.1,)
loader_version_range = [4,)

parchment_minecraft_version = 1.21.1
parchment_mappings_version = 2024.11.17

curios_version = 9.5.1+1.21.1
iris_version = 1.8.12+1.21.1-neoforge

version=1.21.1-1.0.169
